import NavBar from "@/components/NavBar";
import SidePanel from "@/components/SidePanel";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex  flex-row">
      <SidePanel />
      <div className="w-full flex flex-col">
        <NavBar/>
        {children}
        </div>
    </div>
  );
}
